version: '3.4'

services:
  mysql:
    image: mysql:5.7.8
    command: --default-authentication-plugin=mysql_native_password --sql_mode=""
    restart: always
    profiles: 
      - backend
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=hexagonal
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=hexagonal
    volumes:
      - hexagonal-mysql-data:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD

volumes:
  hexagonal-mysql-data: {}