apiVersion: apps/v1
kind: Deployment
metadata:
  name: relay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: relay
  template:
    metadata:
      labels:
        app: relay
    spec:
      containers:
        - name: relay
          envFrom:
            - configMapRef:
                name: app-saga-conf
          image: 395271362395.dkr.ecr.ap-northeast-2.amazonaws.com/relay
          resources:
            requests:
              cpu: 125m
              memory: 128Mi
          ports:
            - containerPort: 8090
