apiVersion: apps/v1
kind: Deployment
metadata:
  name: flight
spec:
  replicas: 1
  selector:
    matchLabels:
      service: flight
  template:
    metadata:
      labels:
        service: flight
    spec:
      serviceAccount: app-service-account
      containers:
        - name: flight
          envFrom:
            - configMapRef:
                name: app-conf
          image: FLIGHT_IMAGE
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 125m
              memory: 128Mi
            limits:
              cpu: 256m
              memory: 512Mi
          ports:
            - containerPort: 8090
