apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel
spec:
  replicas: 1
  selector:
    matchLabels:
      service: hotel
  template:
    metadata:
      labels:
        service: hotel
    spec:
      containers:
        - name: hotel
          envFrom:
            - configMapRef:
                name: app-conf
          image: HOTEL_IMAGE
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 125m
              memory: 128Mi
            limits:
              cpu: 256m
              memory: 512Mi
          ports:
            - containerPort: 8090
