apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - car.yaml
  - flight.yaml
  - hotel.yaml
  - relay.yaml
  - saga.yaml
  - trip.yaml
commonLabels:
  app: saga-demo
configMapGenerator:
  - name: saga-demo-conf
    files:
      - application.properties
