apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - car.yaml
  - flight.yaml
  - hotel.yaml
  - relay.yaml
  - saga.yaml
  - trip.yaml
  - service-account.yaml
  - migration.yaml
configMapGenerator:
  - name: app-conf
    envs:
      - app.env
commonLabels:
  app.kubernetes.io/type: app
  app.kubernetes.io/app: saga