apiVersion: batch/v1
kind: Job
metadata:
  name: migration
spec:
  ttlSecondsAfterFinished: 60
  template:
    spec:
      serviceAccount: app-service-account
      containers:
      - name: migration
        image: MIGRATION_IMAGE
        imagePullPolicy: Always
      restartPolicy: Never
