apiVersion: batch/v1
kind: Job
metadata:
  name: migration
spec:
  ttlSecondsAfterFinished: 60
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: batch
        app.kubernetes.io/name: migration
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccount: app-service-account
      containers:
      - name: migration
        image: MIGRATION_IMAGE
        imagePullPolicy: Always
      restartPolicy: Never
