apiVersion: batch/v1
kind: Job
metadata:
  name: migration
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: batch
        app.kubernetes.io/name: migration
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      completions: 1
      parallelism: 1
      serviceAccount: app-service-account
      containers:
      - name: migration
        image: MIGRATION_IMAGE
        imagePullPolicy: IfNotPresent
      restartPolicy: Never
