apiVersion: apps/v1
kind: Deployment
metadata:
  name: relay
spec:
  replicas: 1
  selector:
    matchLabels:
      service: relay
  template:
    metadata:
      labels:
        service: relay
    spec:
      containers:
        - name: relay
          envFrom:
            - configMapRef:
                name: app-conf
          image: RELAY_IMAGE
          resources:
            requests:
              cpu: 125m
              memory: 128Mi
            limits:
              cpu: 256m
              memory: 512Mi
          ports:
            - containerPort: 8090
