apiVersion: apps/v1
kind: Deployment
metadata:
  name: relay
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: service
      app.kubernetes.io/instance: app
      app.kubernetes.io/name: relay
  template:
    metadata:
      labels:
        app.kubernetes.io/component: service
        app.kubernetes.io/instance: app
        app.kubernetes.io/name: relay
    spec:
      serviceAccount: app-service-account
      containers:
        - name: relay
          envFrom:
            - configMapRef:
                name: app-conf
          image: RELAY_IMAGE
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 125m
              memory: 128Mi
            limits:
              cpu: 256m
              memory: 512Mi
          ports:
            - containerPort: 8090
          livenessProbe:
            httpGet:
              path: /healthy
              port: 8090
            initialDelaySeconds: 30
            periodSeconds: 5