apiVersion: apps/v1
kind: Deployment
metadata:
  name: saga
spec:
  replicas: 1
  selector:
    matchLabels:
      service: saga
  template:
    metadata:
      labels:
        service: saga
    spec:
      containers:
        - name: saga
          envFrom:
            - configMapRef:
                name: app-conf
          image: SAGA_IMAGE
          resources:
            requests:
              cpu: 125m
              memory: 128Mi
            limits:
              cpu: 256m
              memory: 512Mi
          ports:
            - containerPort: 8090
