apiVersion: apps/v1
kind: Deployment
metadata:
  name: trip
spec:
  replicas: 1
  selector:
    matchLabels:
      service: trip
  template:
    metadata:
      labels:
        service: trip
    spec:
      containers:
        - name: trip
          envFrom:
            - configMapRef:
                name: app-conf
          image: TRIP_IMAGE
          resources:
            requests:
              cpu: 125m
              memory: 128Mi
          ports:
            - containerPort: 8090
---
apiVersion: v1
kind: Service
metadata:
  name: trip
spec:
  ports:
    - port: 80
      targetPort: 8090
  selector:
    service: trip
