apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: CAR_IMAGE
    newName: 395271362395.dkr.ecr.ap-northeast-2.amazonaws.com/car
    newTag: f1d781ff52
  - name: HOTEL_IMAGE
    newName: 395271362395.dkr.ecr.ap-northeast-2.amazonaws.com/hotel
    newTag: f1d781ff52
  - name: FLIGHT_IMAGE
    newName: 395271362395.dkr.ecr.ap-northeast-2.amazonaws.com/flight
    newTag: f1d781ff52
  - name: RELAY_IMAGE
    newName: 395271362395.dkr.ecr.ap-northeast-2.amazonaws.com/relay
    newTag: f1d781ff52
  - name: SAGA_IMAGE
    newName: 395271362395.dkr.ecr.ap-northeast-2.amazonaws.com/saga
    newTag: f1d781ff52
  - name: TRIP_IMAGE
    newName: 395271362395.dkr.ecr.ap-northeast-2.amazonaws.com/trip
    newTag: f1d781ff52
configMapGenerator:
  - name: aws-conf
    envs:
      - .env
patchesStrategicMerge:
  - patch-env-trip.yaml
commonLabels:
  stage: dev
