apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: CAR_IMAGE
    newName: 395271362395.dkr.ecr.ap-northeast-2.amazonaws.com/car
    newTag: 773687887a
  - name: HOTEL_IMAGE
    newName: 395271362395.dkr.ecr.ap-northeast-2.amazonaws.com/hotel
    newTag: 773687887a
  - name: FLIGHT_IMAGE
    newName: 395271362395.dkr.ecr.ap-northeast-2.amazonaws.com/flight
    newTag: 773687887a
  - name: RELAY_IMAGE
    newName: 395271362395.dkr.ecr.ap-northeast-2.amazonaws.com/relay
    newTag: 773687887a
  - name: SAGA_IMAGE
    newName: 395271362395.dkr.ecr.ap-northeast-2.amazonaws.com/saga
    newTag: 773687887a
  - name: TRIP_IMAGE
    newName: 395271362395.dkr.ecr.ap-northeast-2.amazonaws.com/trip
    newTag: 773687887a
  - name: MIGRATION_IMAGE
    newName: 395271362395.dkr.ecr.ap-northeast-2.amazonaws.com/migration
    newTag: 773687887a
configMapGenerator:
  - name: aws-conf
    envs:
      - aws.env
patchesStrategicMerge:
  - patch-env-trip.yaml
  - patch-env-car.yaml
  - patch-env-hotel.yaml
  - patch-env-flight.yaml
  - patch-env-saga.yaml
  - patch-env-relay.yaml
  - patch-env-migration.yaml
commonLabels:
  app.kubernetes.io/stage: dev
