apiVersion: apps/v1
kind: Deployment
metadata:
  name: saga
spec:
  template:
    spec:
      containers:
        - name: saga
          envFrom:
            - configMapRef:
                name: app-conf
            - configMapRef:
                name: aws-conf