apiVersion: apps/v1
kind: Deployment
metadata:
  name: migration
spec:
  template:
    spec:
      containers:
        - name: migration
          envFrom:
            - configMapRef:
                name: app-conf
            - configMapRef:
                name: aws-conf