apiVersion: apps/v1
kind: Deployment
metadata:
  name: car
  app.kubernetes.io/type: app
spec:
  template:
    spec:
      containers:
        - name: car
          envFrom:
            - configMapRef:
                name: app-conf
            - configMapRef:
                name: aws-conf