apiVersion: apps/v1
kind: Deployment
metadata:
  name: trip
spec:
  template:
    spec:
      containers:
        - name: trip
          envFrom:
            - configMapRef:
                name: aws-conf