apiVersion: apps/v1
kind: Deployment
metadata:
  name: flight
  app.kubernetes.io/type: app
spec:
  template:
    spec:
      containers:
        - name: flight
          envFrom:
            - configMapRef:
                name: app-conf
            - configMapRef:
                name: aws-conf