apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trip
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: kube/overlays/dev
    repoURL: https://git-codecommit.ap-northeast-2.amazonaws.com/v1/repos/saga-demo-app
    targetRevision: HEAD
  syncPolicy:
    automated:
      allowEmpty: false
      prune: true
      selfHeal: true
  revisionHistoryLimit: 3
